
skillMetadata:
  sections:
    - name: Options
      fields:
        - name: internal_python_variable_name
          type: text
          label: This does nothong yet. Yet
          value: ""
          placeholder: demo prompt in the input box
    - name: nothing to "save" here.
      fields:
        - type: label
          label: Just a little bit of extra stuff to figure
        - name: username
          type: text
          label: Username
          value: ""
        - name: password
          type: password
          label: Password
          value: ""
